---
title: ''
author: "李欣鹏PB20030804"
output: html_document
---

```{r, include = FALSE}
# output:
# pdf_document:
# latex_engine: xelatex
#
# header-includes:
#   - \usepackage{ctex}
```

```{r setup, include=FALSE}

library(tidyverse)
library(lubridate)
library(knitr)
library(corrplot)
library(sysfonts)
library(showtextdb)
library(showtext)
library(magrittr)
library(tidyselect)
library(cowplot)
library(ggrepel)

opts_chunk$set(echo      = TRUE,
               # results   = 'hold',
               message   = FALSE, warning = FALSE,
               cache     = TRUE, cache.lazy = FALSE,
               fig.align = 'center')


theme_set(theme_bw(12))

```


# Bootstrap函数

```{r bootstrap}
## Unils for handling different type of samples
source('SamUtils.R')

available.bootstrap.methods <- c('normal', 'basic', 'percentile')

#######################################################
# Bootstrap resampling mathod                         #
#                                                     #
# x      - Samples, vector, matrix or data.frame      #
# stat   - Estimator to use, accepts the same type    #
#          of arguments as `x', and produces a number #
# size   - Resampling size                            #
# method - Method used to compute confidence interval #
#                                                     #
# @return - List of entries: est, lower and upper     #
#######################################################
bootstrap.ci <-
  function (
    x,
    stat,
    size = 100,
    level = 0.95,
    method = available.bootstrap.methods
  )
  {
    alpha <- 1 - level
    stopifnot(between(alpha, 0, 1))

    x_ <- make_sample(x)
    n_ <- sample_size(x)

    bs.x <- map_dbl(seq_len(size),
                    function (i) {
                      ii <- sample(n_, n_, TRUE)
                      stat(x_(ii))
                    })

    method <- method[1]
    if (method == 'normal') {
      bs.est   <- mean(bs.x)
      bs.sd    <- sd(bs.x)
      z        <- qnorm(alpha / 2)
      bs.hlen  <- z * bs.sd
      bs.lower <- bs.est + bs.hlen
      bs.upper <- bs.est - bs.hlen
    } else if (method == 'basic') {
      est_     <- stat(x)
      bs.est   <- est_
      bs.diff  <- bs.x - est_
      qdiff    <- quantile(bs.diff,
                           probs = c(alpha / 2,
                                     1 - alpha / 2),
                           names = FALSE)
      bs.lower <- est_ + qdiff[1]
      bs.upper <- est_ + qdiff[2]
    } else if (method == 'percentile') {
      bs.est   <- mean(bs.x)
      qbsx     <- quantile(bs.x,
                           probs = c(alpha / 2,
                                     1 - alpha / 2),
                           names = FALSE)
      bs.lower <- qbsx[1]
      bs.upper <- qbsx[2]
    } else {
      stop('Unknown method: ', method)
    }
    list(est   = bs.est,
         lower = bs.lower,
         upper = bs.upper)
  }
```



# TEST

```{r test}
set.seed(114514)

x <- rchisq(100, 5)

map_dfr(c('normal', 'basic', 'percentile'),
        function (m) {
          set.seed(114514)
          bootstrap.ci(x, mean, method = m) |>
            unlist() |>
            c(Method = m)
        }) |>
  kable(align = 'c')
```


# 覆盖率

```{r coverage}

bootstrap.coverage <-
  function (r.fun, stat, par.true, ci.fun,
            n.sample = 100,
            n.mc = 100,
            n.bs = 100,
            levels = c(.90, .95, .99),
            methods = available.bootstrap.methods) {
    r.fun  <- rlang::as_function(r.fun)
    ci.fun <- rlang::as_function(ci.fun)
    pmap_dfr(
      expand_grid(level = levels, method = methods),
      function (level, method) {
        par.inside <- double(n.mc)
        lower.miss <- double(n.mc)
        upper.miss <- double(n.mc)
        walk(1:n.mc, function (ii) {
          x              <- r.fun(n.sample)
          ci             <- bootstrap.ci(x, stat, n.bs, level, method)
          ci_            <- ci.fun(level)
          par.inside[ii] <<- between(par.true, ci$lower, ci$upper)
          lower.miss[ii] <<- ci$lower > ci_[[1]]
          upper.miss[ii] <<- ci$upper < ci_[[2]]
        })
        c(Method          = method, Level = level,
          'Coverage Rate' = mean(par.inside),
          'Lower Miss'    = mean(lower.miss),
          'Upper Miss'    = mean(upper.miss))
      }
    )
  }

```

## 示例

### $\chi^2_5$

```{r chisq5}
bootstrap.coverage(
  ~rchisq(., 5),
  mean,
  5,
  ~qchisq(c((1 - .) / 2, 1 - (1 - .) / 2), 1500) / 300,
  n.sample = 300, n.mc = 500, n.bs = 100
) |>
  kable(align = 'c')
```

### $\chi^2_{20}$

```{r chisq20}
bootstrap.coverage(
  ~rchisq(., 20),
  mean,
  20,
  ~qchisq(c((1 - .) / 2, 1 - (1 - .) / 2), 300 * 20) / 300,
  n.sample = 300, n.mc = 500, n.bs = 100
) |>
  kable(align = 'c')
```

